### ISSUE TITLE
Percentage display in OnlineMembers Count

### ISSUE THREAD

**Issue by TheChaosToast** [DrWarpMan/sinusbot-scripts#3]
Hello my friend,

I am currently using 2 scripts from you: OnlineMembersCount and OnlineClients in Server Name. Both scripts work very well and do what they want;)

Now I have seen (mainly on Polish servers) that in both cases the "utilization" in percent is behind it. Are these modified scripts? I would want this one too :)

Thanks for an answer :)

**Comment by DrWarpMan** [comment]
I can do it in the Online Clients in Server Name script, but currently OnlineMembersCount is coded in a way, that it is not easily implementable at the moment, and I am afraid I don't have much time to recode it now.

But as I said, I can do it at least in the server name script, are you satisfied with that?

**Comment by TheChaosToast** [comment]
Yes, that would be enough for me for now, the other has time and is not in a hurry. Thank you for your help :)

**Comment by DrWarpMan** [comment]
Can you try it out?

Use %percentage% in the name.
It only gives you the number, you will have to add the sign % at the end by yourself.

https://github.com/DrWarpMan/sinusbot-scripts/blob/master/scripts/onlineClientsInServerName.js

**Comment by TheChaosToast** [comment]
hey my friend, your script works wonderfully. i tested it on my test server. if something does not work, I will contact you, but I do not assume that :)

**Comment by DrWarpMan** [comment]
Forgot to close the issue.

Feature added, seems to be working.
